core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.UserCreationView.as_view(), name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('', views.IndexView.as_view(), name='index'),
    path('course_detail_view/<int:pk>/', views.CourseDetailView.as_view(), name='course_detail_view'),

    path('exam_results/', views.ExamResultListView.as_view(), name='exam_results'),
    path('exam_results/detail/<int:pk>/', views.ExamResultDetailView.as_view(), name='exam_results_detail_view'),
]

examination_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include(('core.urls', 'core'), namespace='core')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/course_detail.html
{% extends 'master.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}
    <div class="col-md-12 mt-4">
        <div class="card">
            <div class="card-header">
                {{ object.title }}
            </div>
            <div class="card-body">
                {{ object.content|safe }}
            </div>
        </div>
    </div>

    <div class="col-md-12 mt-4 mb-4">
        <div class="card">
            <div class="card-header">
                {% translate 'Exam' %}
            </div>
            <div class="card-body">
                <form method='post' action=''>
                    {% csrf_token %}
                    {% for question  in object.exam.questions.all %}
                        <div class="form-group">
                            <label for="question">{{ question.title }}</label>
                        </div>
                        <div class="form-check">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{ question.id }}" id="choice_one" value="1" checked>
                                <label class="form-check-label" for="choice_one">
                                    {{ question.choice_one }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{ question.id }}" id="choice_two" value="2">
                                <label class="form-check-label" for="choice_two">
                                    {{ question.choice_two }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{ question.id }}" id="choice_three" value="3">
                                <label class="form-check-label" for="choice_three">
                                    {{ question.choice_three }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{ question.id }}" id="choice_four" value="4">
                                <label class="form-check-label" for="choice_four">
                                    {{ question.choice_four }}
                                </label>
                            </div>
                            <br>
                        </div>

                        <hr class="mb-5">
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">
                        {% translate 'Submit' %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/course_detail_bootstrap.html
{% extends 'master.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}
    <div class="col-md-12 mt-4">
        <div class="card">
            <div class="card-header">
                {{ object.title }}
            </div>
            <div class="card-body">
                {{ object.content|safe }}
            </div>
        </div>
    </div>

    <div class="col-md-12 mt-4 mb-4">
        <div class="card">
            <div class="card-header">
                {% translate 'Exam' %}
            </div>
            <div class="card-body">
                <form method='post' action=''>
                    {% csrf_token %}
                    {% for question  in object.exam.questions.all %}
                        <div class="form-group">
                            <label for="question">{{ question.title }}</label>
                        </div>
                        <div class="form-check">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{ question.id }}" id="choice_one" value="1" checked>
                                <label class="form-check-label" for="choice_one">
                                    {{ question.choice_one }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{ question.id }}" id="choice_two" value="2">
                                <label class="form-check-label" for="choice_two">
                                    {{ question.choice_two }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{ question.id }}" id="choice_three" value="3">
                                <label class="form-check-label" for="choice_three">
                                    {{ question.choice_three }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{ question.id }}" id="choice_four" value="4">
                                <label class="form-check-label" for="choice_four">
                                    {{ question.choice_four }}
                                </label>
                            </div>
                            <br>
                        </div>

                        <hr class="mb-5">
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">
                        {% translate 'Submit' %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/exam_result_Bootstrap.html
{% extends 'master.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {{ object }}
{% endblock %}

{% block content %}
    <div class="col-md-12 mt-4">
        <div class="card">
            <div class="card-header">
                {{ object }}
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% translate 'Question' %}</th>
                        <th scope="col">{% translate 'User Answer' %}</th>
                        <th scope="col">{% translate 'Correct Answer' %}</th>
                        <th scope="col">{% translate 'Answer is Correct' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object.result %}
                        <tr>
                            <th scope="row">{{ object.question_id }}</th>
                            <td>{{ object.question }}</td>
                            <td>{{ object.user_answer }}</td>
                            <td>{{ object.correct_answer }}</td>
                            <td>{{ object.answer_is_correct|yesno:"Yes,No" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col">
                        {% translate 'Wrong Count' %} : {{ object.wrong_count }}
                    </div>
                    <div class="col">
                        {% translate 'Correct Count' %} : {{ object.correct_count }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/exam_result_detail.html
{% extends 'master.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {{ object }}
{% endblock %}

{% block content %}
    <div class="col-md-12 mt-4">
        <div class="card">
            <div class="card-header">
                {{ object }}
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% translate 'Question' %}</th>
                        <th scope="col">{% translate 'User Answer' %}</th>
                        <th scope="col">{% translate 'Correct Answer' %}</th>
                        <th scope="col">{% translate 'Answer is Correct' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object.result %}
                        <tr>
                            <th scope="row">{{ object.question_id }}</th>
                            <td>{{ object.question }}</td>
                            <td>{{ object.user_answer }}</td>
                            <td>{{ object.correct_answer }}</td>
                            <td>{{ object.answer_is_correct|yesno:"Yes,No" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col">
                        {% translate 'Wrong Count' %} : {{ object.wrong_count }}
                    </div>
                    <div class="col">
                        {% translate 'Correct Count' %} : {{ object.correct_count }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/exam_result_list.html
{% extends 'master.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% translate 'Exam Results' %}
{% endblock %}

{% block content %}
    <div class="col-md-12 mt-4">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{% translate 'Course' %}</th>
                <th scope="col">{% translate 'Exam' %}</th>
                <th scope="col">{% translate 'Wrong Count' %}</th>
                <th scope="col">{% translate 'Correct Count' %}</th>
                <th scope="col">{% translate 'Create Time' %}</th>
                <th scope="col">{% translate 'Actions' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <th scope="row">{{ object.id }}</th>
                    <td>{{ object.course }}</td>
                    <td>{{ object.exam }}</td>
                    <td>{{ object.wrong_count }}</td>
                    <td>{{ object.correct_count }}</td>
                    <td>{{ object.create_time }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'core:exam_results_detail_view' object.id %}">
                            {% translate 'Result' %}
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/index.html
{% extends 'master.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% translate 'Index' %}
{% endblock %}

{% block content %}
    {% for object in object_list %}
        <div class="col-md-4 mt-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">{{ object.description }}</p>
                    <a href="{% url 'core:course_detail_view' object.id %}" class="btn btn-primary">
                        {% translate 'Go To Course' %}
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/master.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% block custom_style %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'core:index' %}">{% translate 'Examination System' %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_content"
            aria-controls="navbar_content" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar_content">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:index' %}">{% translate 'Home' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:exam_results' %}">{% translate 'Exam results' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:logout' %}">{% translate 'Logout' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:login' %}">{% translate 'Login' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:signup' %}">{% translate 'Signup' %}</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% block custom_script %}
{% endblock %}

</body>
</html>